max_frames: 600
max_epoch: 5
batch_size: 50
margin: 0.5

eval_frames: 400
augment: True

## Training details
trainfunc: aamsoftmax

scale: 30

lr: 5e-4
lr_decay: 0.95

pretrained_model_path: WavLM-Base+.pt
weight_finetuning_reg: 0.01
LLRD_factor: 1.0
LR_Transformer: 2e-5
LR_MHFA: 5e-3

## Loss functions
nClasses: 7500

## Load and save
save_path: exp/wavlm_mhfa_dlg_lc_lmft

## Model definition
model: Baseline.Spk_Encoder

nOut: 256
port: 6754
